# Generated by Django 5.2.4 on 2025-08-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'ordering': ['ordering', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=155, verbose_name='site name')),
                ('footer_text', models.CharField(blank=True, max_length=155, verbose_name='footer text')),
                ('footer_contact_phone', models.CharField(blank=True, max_length=55, verbose_name='footer contact phone')),
                ('footer_contact_text', models.CharField(blank=True, max_length=155, verbose_name='footer contact text')),
                ('footer_github_link', models.URLField(blank=True, max_length=100, verbose_name='footer github link')),
                ('footer_telegram_link', models.URLField(blank=True, max_length=100, verbose_name='footer telegram link')),
                ('footer_linkedin_link', models.URLField(blank=True, max_length=100, verbose_name='footer linkedin link')),
                ('footer_instagram_link', models.URLField(blank=True, max_length=100, verbose_name='footer instagram link')),
            ],
        ),
        migrations.CreateModel(
            name='MiddleBanners',
            fields=[
                ('basebanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basebanner')),
            ],
            bases=('core.basebanner',),
        ),
        migrations.CreateModel(
            name='SideBanners',
            fields=[
                ('basebanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basebanner')),
            ],
            bases=('core.basebanner',),
        ),
        migrations.CreateModel(
            name='SliderBanners',
            fields=[
                ('basebanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basebanner')),
            ],
            bases=('core.basebanner',),
        ),
        migrations.AddField(
            model_name='basebanner',
            name='site_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.sitesettings'),
        ),
    ]
