# Generated by Django 5.2.4 on 2025-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_basebanner_sitesettings_middlebanners_sidebanners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebanner',
            name='title',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
