# Generated by Django 5.2.4 on 2025-08-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
