# Generated by Django 5.2.5 on 2025-08-29 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155, verbose_name='full_name')),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(default='Iran', max_length=60, verbose_name='country')),
                ('state', models.CharField(blank=True, max_length=60, verbose_name='state/province')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('full_address', models.TextField()),
                ('is_default', models.BooleanField(default=False, verbose_name='user default address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('fulfilled', 'Fulfilled / Shipped'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=32, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('cod', 'Cash on Delivery'), ('transfer', 'Bank Transfer / EFT')], default='card', max_length=16, verbose_name='payment method')),
                ('shipping_method', models.CharField(choices=[('fast', 'Fast Delivery'), ('normal', 'Normal Delivery'), ('economy', 'Economy Delivery')], default='normal', max_length=20)),
                ('subtotal', models.PositiveIntegerField(verbose_name='subtotal')),
                ('discount_total', models.PositiveIntegerField(verbose_name='discount total')),
                ('shipping_total', models.PositiveIntegerField(verbose_name='shipping')),
                ('tax_total', models.PositiveIntegerField(verbose_name='tax total')),
                ('grand_total', models.PositiveIntegerField(verbose_name='grand total')),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='coupon code')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.address', verbose_name='shipping address record')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=155, verbose_name='product name')),
                ('item_price', models.PositiveIntegerField(verbose_name='item price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('total_discount', models.PositiveIntegerField(verbose_name='total discount')),
                ('final_price', models.PositiveIntegerField(verbose_name='final price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_orders', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_order_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
    ]
