# Generated by Django 5.2.5 on 2025-08-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_line1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_line2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_state',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='user default address'),
        ),
    ]
