# Generated by Django 5.2.5 on 2025-08-20 05:35

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_full_name', models.CharField(max_length=120, verbose_name='recipient name')),
                ('ship_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ship_country', models.CharField(default='iran', max_length=60, verbose_name='country')),
                ('ship_state', models.CharField(blank=True, max_length=60, verbose_name='state/province')),
                ('ship_city', models.CharField(max_length=60, verbose_name='city')),
                ('ship_postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('ship_line1', models.CharField(max_length=255, verbose_name='address line 1')),
                ('ship_line2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled / Shipped'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=32, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('cod', 'Cash on Delivery'), ('transfer', 'Bank Transfer / EFT')], max_length=16, verbose_name='payment method')),
                ('subtotal', models.PositiveIntegerField(verbose_name='subtotal')),
                ('discount_total', models.PositiveIntegerField(verbose_name='discount total')),
                ('shipping_total', models.PositiveIntegerField(verbose_name='shipping')),
                ('tax_total', models.PositiveIntegerField(verbose_name='tax total')),
                ('grand_total', models.PositiveIntegerField(verbose_name='grand total')),
                ('coupon_code', models.CharField(blank=True, max_length=40, verbose_name='coupon code')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.address', verbose_name='shipping address record')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
