# Generated by Django 5.2.5 on 2025-08-20 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_address_user_order'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=155, verbose_name='product name')),
                ('item_price', models.PositiveIntegerField(verbose_name='item price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('total_price', models.PositiveIntegerField(verbose_name='total_price')),
                ('total_discount', models.PositiveIntegerField(verbose_name='total discount')),
                ('final_price', models.PositiveIntegerField(verbose_name='final price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_orders', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_order_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
