# Generated by Django 5.2.5 on 2025-08-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_options_remove_order_ship_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='full_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_address',
        ),
    ]
