# Generated by Django 5.2.5 on 2025-08-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
