# Generated by Django 5.2.5 on 2025-08-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('fast', 'Fast Delivery'), ('normal', 'Normal Delivery'), ('economy', 'Economy Delivery')], default='normal', max_length=20),
        ),
    ]
