# Generated by Django 5.2.5 on 2025-08-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_address_address_full_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='coupon code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('cod', 'Cash on Delivery'), ('transfer', 'Bank Transfer / EFT')], default='card', max_length=16, verbose_name='payment method'),
        ),
    ]
