# Generated by Django 5.2.5 on 2025-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('fast', 'Fast Delivery'), ('normal', 'Normal Delivery'), ('economy', 'Economy Delivery')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
