# Generated by Django 5.2.5 on 2025-08-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('fast', 'Fast Delivery'), ('normal', 'Normal Delivery'), ('economy', 'Economy Delivery')], default='card', max_length=20),
        ),
    ]
