# Generated by Django 5.2.5 on 2025-08-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('fulfilled', 'Fulfilled / Shipped'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=32, verbose_name='status'),
        ),
    ]
