# Generated by Django 5.2.5 on 2025-08-25 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='value')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='expire date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug')),
                ('main_image', models.ImageField(upload_to='products/')),
                ('short_description', models.CharField(max_length=155, verbose_name='short description')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('status', models.CharField(choices=[('a', 'Available'), ('s', 'Coming Soon'), ('na', 'Not Available')], max_length=2, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='categories.brand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='categories.category', verbose_name='category')),
                ('discount', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_products', to='products.discount', verbose_name='discount')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('c', 'Color'), ('s', 'Size')], max_length=1, verbose_name='feature')),
                ('color', models.CharField(blank=True, choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('black', 'black'), ('white', 'white'), ('yellow', 'yellow'), ('orange', 'orange'), ('purple', 'purple'), ('pink', 'pink'), ('brown', 'brown'), ('gray', 'gray'), ('silver', 'silver'), ('gold', 'gold'), ('beige', 'beige'), ('maroon', 'maroon'), ('navy', 'navy'), ('teal', 'teal'), ('turquoise', 'turquoise'), ('cyan', 'cyan'), ('magenta', 'magenta'), ('lime', 'lime'), ('olive', 'olive'), ('indigo', 'indigo'), ('violet', 'violet'), ('coral', 'coral'), ('salmon', 'salmon'), ('khaki', 'khaki'), ('mint', 'mint'), ('peach', 'peach'), ('ivory', 'ivory'), ('lavender', 'lavender')], help_text='If this feature is a color, fill this field and leave the value field empty.', max_length=20, verbose_name='color')),
                ('value', models.CharField(blank=True, help_text='If this feature is a size, fill this field and leave the color field empty.', max_length=55, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_options', to='products.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('text', models.TextField()),
                ('recommend', models.BooleanField()),
                ('status', models.CharField(choices=[('aprv', 'APPROVED'), ('drf', 'draft'), ('rjk', 'rejected')], default='drf', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='products.comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=55, verbose_name='key')),
                ('value', models.CharField(max_length=155, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'unique_together': {('product', 'key')},
            },
        ),
    ]
