# Generated by Django 5.2.5 on 2025-08-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sell',
            field=models.PositiveIntegerField(default=0, verbose_name='total_sell'),
        ),
    ]
