# Generated by Django 5.2.4 on 2025-08-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('c', 'Color'), ('s', 'Size')], max_length=1, verbose_name='feature')),
                ('color', models.CharField(blank=True, choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('black', 'black'), ('white', 'white'), ('yellow', 'yellow'), ('orange', 'orange'), ('purple', 'purple'), ('pink', 'pink'), ('brown', 'brown'), ('gray', 'gray'), ('silver', 'silver'), ('gold', 'gold'), ('beige', 'beige'), ('maroon', 'maroon'), ('navy', 'navy'), ('teal', 'teal'), ('turquoise', 'turquoise'), ('cyan', 'cyan'), ('magenta', 'magenta'), ('lime', 'lime'), ('olive', 'olive'), ('indigo', 'indigo'), ('violet', 'violet'), ('coral', 'coral'), ('salmon', 'salmon'), ('khaki', 'khaki'), ('mint', 'mint'), ('peach', 'peach'), ('ivory', 'ivory'), ('lavender', 'lavender')], help_text='If this feature is a color, fill this field and leave the value field empty.', max_length=20, verbose_name='color')),
                ('value', models.CharField(blank=True, help_text='If this feature is a size, fill this field and leave the color field empty.', max_length=55, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_options', to='products.product', verbose_name='product')),
            ],
        ),
    ]
