# Generated by Django 5.2.4 on 2025-08-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='value')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='expire date')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
    ]
