# Generated by Django 5.2.4 on 2025-08-04 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
    ]
