# Generated by Django 5.2.4 on 2025-08-06 13:58

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to=products.models.product_image_upload_path),
        ),
    ]
